import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:palette_generator/palette_generator.dart';
import '../main.dart';
import '../providers/player_provider.dart';
import '../widgets/rotating_glowing_border.dart';
import '../widgets/smooth_button.dart';
import '../screens/artist_screen.dart';
import '../providers/sleep_timer_provider.dart';

class NowPlayingScreen extends ConsumerStatefulWidget {
  const NowPlayingScreen({super.key});

  @override
  ConsumerState<NowPlayingScreen> createState() => _NowPlayingScreenState();
}

class _NowPlayingScreenState extends ConsumerState<NowPlayingScreen> {
  Color _dominantColor = Colors.transparent;
  String? _lastThumbnailUrl;

  @override
  void initState() {
    super.initState();
    // Delay slightly to let the first context build, then fetch palette
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _updatePalette(ref.read(currentTrackProvider)?.thumbnail);
    });
  }

  Future<void> _updatePalette(String? thumbnailUrl) async {
    if (thumbnailUrl == null) {
      if (mounted) setState(() => _dominantColor = kBgDark);
      return;
    }
    
    // Only fetch if image is new 
    if (_lastThumbnailUrl == thumbnailUrl) return;
    _lastThumbnailUrl = thumbnailUrl;

    try {
      final palette = await PaletteGenerator.fromImageProvider(
        NetworkImage(thumbnailUrl),
        maximumColorCount: 10,
      );
      
      final color = palette.vibrantColor?.color ?? 
                    palette.dominantColor?.color ?? 
                    kAccent.withOpacity(0.5);

      if (mounted) {
        setState(() {
          _dominantColor = color;
        });
      }
    } catch (e) {
      if (mounted) setState(() => _dominantColor = kBgDark);
    }
  }

  String _fmt(Duration? d) {
    if (d == null) return '--:--';
    final m = d.inMinutes.remainder(60).toString().padLeft(2, '0');
    final s = d.inSeconds.remainder(60).toString().padLeft(2, '0');
    return '$m:$s';
  }

  @override
  Widget build(BuildContext context) {
    final track = ref.watch(currentTrackProvider);
    final isPlaying = ref.watch(playingStreamProvider).valueOrNull ?? false;
    final position =
        ref.watch(positionStreamProvider).valueOrNull ?? Duration.zero;
    final duration = ref.watch(durationStreamProvider).valueOrNull;
    final buffered =
        ref.watch(bufferedPositionStreamProvider).valueOrNull ?? Duration.zero;
    final shuffle = ref.watch(shuffleProvider);
    final repeatMode = ref.watch(repeatModeProvider);
    final sleepTimer = ref.watch(sleepTimerProvider);
    
    final screenWidth = MediaQuery.of(context).size.width;
    final isMobile = screenWidth < 800;

    if (track == null) {
      return Scaffold(
        appBar: AppBar(leading: const BackButton()),
        body: const Center(child: Text('No track selected')),
      );
    }
    
    // Check if track changed to trigger palette update
    if (track.thumbnail != _lastThumbnailUrl) {
      _updatePalette(track.thumbnail);
    }

    return Scaffold(
      body: Stack(
        children: [
          // 1. The Background Layer (Lowest in Stack):
          // Dynamic gradient (generated by palette_generator) filling entire screen
          Positioned.fill(
            child: AnimatedContainer(
              duration: const Duration(milliseconds: 800),
              curve: Curves.easeInOut,
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment.topLeft,
                  end: Alignment.bottomRight,
                  colors: [
                    _dominantColor,
                    _dominantColor.withOpacity(0.3),
                    Colors.black,
                  ],
                  stops: const [0.0, 0.4, 1.0],
                ),
              ),
            ),
          ),

          // 2. The Foreground UI (Top of Stack)
          SafeArea(
            child: SingleChildScrollView(
              child: Column(
                children: [
                // Top bar
                Padding(
                  padding:
                      const EdgeInsets.symmetric(horizontal: 20, vertical: 8),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      SmoothButton(
                      onTap: () => Navigator.pop(context),
                      child: const Icon(Icons.keyboard_arrow_down_rounded,
                          size: 32, color: kTextWhite),
                    ),
                    const Text(
                      'Now Playing',
                      style: TextStyle(
                        fontSize: 14,
                        fontWeight: FontWeight.w600,
                        color: kTextWhite,
                      ),
                    ),
                    Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        SmoothButton(
                          onTap: () {
                            _showSleepTimerMenu(context, ref, sleepTimer);
                          },
                          child: Icon(Icons.bedtime_outlined, 
                            color: sleepTimer.mode != SleepTimerMode.off ? kAccent : kTextWhite),
                        ),
                        SmoothButton(
                          onTap: () {
                            // TODO: Toggle Real-Time Lyrics view
                          },
                          child: const Icon(Icons.lyrics_outlined, color: kTextWhite),
                        ),
                      ],
                    ),
                    ],
                  ),
                ),

                const SizedBox(height: 32),

                // Album art (Keep near the top/center)
                Container(
                  width: isMobile ? screenWidth * 0.75 : 300.0,
                  height: isMobile ? screenWidth * 0.75 : 300.0,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(16),
                    boxShadow: [
                      BoxShadow(
                        color: Colors.black.withOpacity(0.5),
                        blurRadius: 30,
                        offset: const Offset(0, 16),
                      ),
                    ],
                  ),
                  child: ClipRRect(
                    borderRadius: BorderRadius.circular(16),
                    child: track.thumbnail != null
                        ? Image.network(
                            track.thumbnail!,
                            fit: BoxFit.cover,
                            errorBuilder: (_, __, ___) => _placeholder(),
                          )
                        : _placeholder(),
                  ),
                ),

                const SizedBox(height: 32),

                // Title & artist
                Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 40),
                  child: Column(
                    children: [
                      Text(
                        track.title,
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                        textAlign: TextAlign.center,
                        style: const TextStyle(
                          fontSize: 22,
                          fontWeight: FontWeight.w700,
                          color: kTextWhite,
                        ),
                      ),
                      const SizedBox(height: 6),
                      MouseRegion(
                        cursor: SystemMouseCursors.click,
                        child: GestureDetector(
                          onTap: () {
                            Navigator.of(context).push(
                              MaterialPageRoute(
                                builder: (_) =>
                                    ArtistScreen(artistName: track.artist),
                              ),
                            );
                          },
                          child: Text(
                            track.artist,
                            textAlign: TextAlign.center,
                            style: const TextStyle(
                              fontSize: 14,
                              color: kTextWhite,
                              fontWeight: FontWeight.w500,
                              decoration: TextDecoration.underline,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),

                const SizedBox(height: 28),

                // 3. The Glass Pill Implementation
                // Distinct bottom container for controls, visually floating from edges
                Padding(
                  padding: EdgeInsets.all(isMobile ? 16.0 : 24.0),
                  child: ClipRRect(
                    borderRadius: BorderRadius.circular(40.0),
                    child: BackdropFilter(
                      filter: ImageFilter.blur(sigmaX: 25.0, sigmaY: 25.0),
                      child: Container(
                        padding: const EdgeInsets.symmetric(vertical: 20.0),
                        decoration: BoxDecoration(
                          color: Colors.black.withOpacity(0.2), // Smoked glass
                          borderRadius: BorderRadius.circular(40.0),
                          border: Border.all(
                            color: Colors.white.withOpacity(0.15),
                            width: 1.5,
                          ),
                        ),
                        child: Column(
                          children: [
                            // Slider inside glass pill
                            Padding(
                              padding: const EdgeInsets.symmetric(horizontal: 24),
                              child: Column(
                                children: [
                                  SliderTheme(
                                    data: SliderTheme.of(context).copyWith(
                                      trackHeight: 3,
                                      thumbShape: const RoundSliderThumbShape(enabledThumbRadius: 6),
                                      overlayShape: const RoundSliderOverlayShape(overlayRadius: 14),
                                      activeTrackColor: Colors.white,
                                      inactiveTrackColor: Colors.white.withOpacity(0.3),
                                      thumbColor: Colors.white,
                                    ),
                                    child: Slider(
                                      value: position.inMilliseconds.toDouble().clamp(
                                          0, (duration?.inMilliseconds ?? 1).toDouble()),
                                      max: (duration?.inMilliseconds ?? 1).toDouble(),
                                      secondaryTrackValue: buffered.inMilliseconds
                                          .toDouble()
                                          .clamp(
                                              0, (duration?.inMilliseconds ?? 1).toDouble()),
                                      onChanged: (v) => audioHandler
                                          .seek(Duration(milliseconds: v.toInt())),
                                    ),
                                  ),
                                  Padding(
                                    padding: const EdgeInsets.symmetric(horizontal: 8),
                                    child: Row(
                                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                      children: [
                                        Text(_fmt(position),
                                            style: const TextStyle(
                                                fontSize: 11, color: kTextWhite)),
                                        Text(_fmt(duration),
                                            style: const TextStyle(
                                                fontSize: 11, color: kTextWhite)),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            
                            const SizedBox(height: 12),
                            
                            // Buttons inside glass pill
                            Row(
                              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                              children: [
                                // Shuffle
                                SmoothButton(
                                  onTap: () {
                                    ref.read(shuffleProvider.notifier).state = !shuffle;
                                  },
                                  child: Icon(Icons.shuffle_rounded,
                                      color: shuffle ? Colors.white : Colors.white54, size: 26),
                                ),
                                // Skip previous
                                SmoothButton(
                                  onTap: () => skipPrevious(ref),
                                  child: const Icon(Icons.skip_previous_rounded,
                                      color: Colors.white, size: 36),
                                ),
                                // Play/Pause
                                SmoothButton(
                                  onTap: () => isPlaying
                                      ? audioHandler.pause()
                                      : audioHandler.play(),
                                  child: RotatingGlowingBorder(
                                    isPlayingStream: audioHandler.playbackState.map((state) => state.playing),
                                    borderWidth: 3.0,
                                    child: Container(
                                      width: 64,
                                      height: 64,
                                      decoration: BoxDecoration(
                                        shape: BoxShape.circle,
                                        color: Colors.white.withOpacity(0.9),
                                      ),
                                      child: Icon(
                                        isPlaying
                                            ? Icons.pause_rounded
                                            : Icons.play_arrow_rounded,
                                        size: 34,
                                        color: Colors.black,
                                      ),
                                    ),
                                  ),
                                ),
                                // Skip next
                                SmoothButton(
                                  onTap: () => skipNext(ref),
                                  child: const Icon(Icons.skip_next_rounded,
                                      color: Colors.white, size: 36),
                                ),
                                // Repeat
                                SmoothButton(
                                  onTap: () {
                                    ref.read(repeatModeProvider.notifier).state =
                                        (repeatMode + 1) % 3;
                                  },
                                  child: Icon(
                                    repeatMode == 2
                                        ? Icons.repeat_one_rounded
                                        : Icons.repeat_rounded,
                                    color: repeatMode > 0 ? Colors.white : Colors.white54,
                                    size: 26,
                                  ),
                                ),
                              ],
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                ),
                const SizedBox(height: 12),
              ],
            ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _placeholder() {
    return Container(
      color: kCardDark,
      child: const Center(
        child: Icon(Icons.music_note_rounded, size: 60, color: kTextMuted),
      ),
    );
  }

  void _showSleepTimerMenu(BuildContext context, WidgetRef ref, SleepTimerState currentTimer) {
    showModalBottomSheet(
      context: context,
      backgroundColor: Colors.transparent,
      builder: (BuildContext sheetContext) {
        return Container(
          padding: const EdgeInsets.symmetric(vertical: 24),
          decoration: BoxDecoration(
            color: kCardDark,
            borderRadius: const BorderRadius.only(
              topLeft: Radius.circular(24),
              topRight: Radius.circular(24),
            ),
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const Text(
                'Sleep Timer',
                style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.w700,
                  color: kTextWhite,
                ),
              ),
              const SizedBox(height: 16),
              if (currentTimer.mode != SleepTimerMode.off) ...[
                Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 8),
                  child: Row(
                    children: [
                      const Icon(Icons.timer_outlined, color: kAccent, size: 18),
                      const SizedBox(width: 12),
                      Text(
                        currentTimer.mode == SleepTimerMode.endOfTrack
                            ? 'Stops after current song'
                            : 'Stops in ${currentTimer.remainingTime?.inMinutes}m ${(currentTimer.remainingTime?.inSeconds ?? 0) % 60}s',
                        style: const TextStyle(color: kAccent, fontWeight: FontWeight.w600),
                      ),
                      const Spacer(),
                      TextButton(
                        onPressed: () {
                          ref.read(sleepTimerProvider.notifier).cancelTimer();
                          Navigator.pop(sheetContext);
                        },
                        child: const Text('Turn Off', style: TextStyle(color: Colors.redAccent)),
                      ),
                    ],
                  ),
                ),
                Divider(color: kDivider),
              ],
              _buildTimerOption(sheetContext, ref, 'End of track', SleepTimerMode.endOfTrack, currentTimer.mode),
              _buildTimerOption(sheetContext, ref, '15 minutes', SleepTimerMode.minutes15, currentTimer.mode),
              _buildTimerOption(sheetContext, ref, '30 minutes', SleepTimerMode.minutes30, currentTimer.mode),
              _buildTimerOption(sheetContext, ref, '45 minutes', SleepTimerMode.minutes45, currentTimer.mode),
              _buildTimerOption(sheetContext, ref, '1 hour', SleepTimerMode.hour1, currentTimer.mode),
              const SizedBox(height: 16),
            ],
          ),
        );
      },
    );
  }

  Widget _buildTimerOption(BuildContext context, WidgetRef ref, String label, SleepTimerMode targetedMode, SleepTimerMode currentMode) {
    final isSelected = targetedMode == currentMode;
    return ListTile(
      title: Text(
        label,
        style: TextStyle(
          color: isSelected ? kAccent : kTextWhite,
          fontWeight: isSelected ? FontWeight.w600 : FontWeight.w400,
        ),
      ),
      trailing: isSelected ? const Icon(Icons.check_rounded, color: kAccent) : null,
      onTap: () {
        ref.read(sleepTimerProvider.notifier).setTimer(targetedMode);
        Navigator.pop(context);
      },
    );
  }
}
