import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:palette_generator/palette_generator.dart';
import '../main.dart';
import '../providers/player_provider.dart';
import '../widgets/rotating_glowing_border.dart';
import '../screens/artist_screen.dart';

class NowPlayingScreen extends ConsumerStatefulWidget {
  const NowPlayingScreen({super.key});

  @override
  ConsumerState<NowPlayingScreen> createState() => _NowPlayingScreenState();
}

class _NowPlayingScreenState extends ConsumerState<NowPlayingScreen> {
  Color _dominantColor = Colors.transparent;
  String? _lastThumbnailUrl;

  @override
  void initState() {
    super.initState();
    // Delay slightly to let the first context build, then fetch palette
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _updatePalette(ref.read(currentTrackProvider)?.thumbnail);
    });
  }

  Future<void> _updatePalette(String? thumbnailUrl) async {
    if (thumbnailUrl == null) {
      if (mounted) setState(() => _dominantColor = kBgDark);
      return;
    }
    
    // Only fetch if image is new 
    if (_lastThumbnailUrl == thumbnailUrl) return;
    _lastThumbnailUrl = thumbnailUrl;

    try {
      final palette = await PaletteGenerator.fromImageProvider(
        NetworkImage(thumbnailUrl),
        maximumColorCount: 10,
      );
      
      final color = palette.vibrantColor?.color ?? 
                    palette.dominantColor?.color ?? 
                    kAccent.withOpacity(0.5);

      if (mounted) {
        setState(() {
          _dominantColor = color;
        });
      }
    } catch (e) {
      if (mounted) setState(() => _dominantColor = kBgDark);
    }
  }

  String _fmt(Duration? d) {
    if (d == null) return '--:--';
    final m = d.inMinutes.remainder(60).toString().padLeft(2, '0');
    final s = d.inSeconds.remainder(60).toString().padLeft(2, '0');
    return '$m:$s';
  }

  @override
  Widget build(BuildContext context) {
    final track = ref.watch(currentTrackProvider);
    final isPlaying = ref.watch(playingStreamProvider).valueOrNull ?? false;
    final position =
        ref.watch(positionStreamProvider).valueOrNull ?? Duration.zero;
    final duration = ref.watch(durationStreamProvider).valueOrNull;
    final buffered =
        ref.watch(bufferedPositionStreamProvider).valueOrNull ?? Duration.zero;
    final shuffle = ref.watch(shuffleProvider);
    final repeatMode = ref.watch(repeatModeProvider);

    if (track == null) {
      return Scaffold(
        appBar: AppBar(leading: const BackButton()),
        body: const Center(child: Text('No track selected')),
      );
    }
    
    // Check if track changed to trigger palette update
    if (track.thumbnail != _lastThumbnailUrl) {
      _updatePalette(track.thumbnail);
    }

    return Scaffold(
      body: Stack(
        children: [
          // 1. The Background Layer (Lowest in Stack):
          // Dynamic gradient (generated by palette_generator) filling entire screen
          Positioned.fill(
            child: AnimatedContainer(
              duration: const Duration(milliseconds: 800),
              curve: Curves.easeInOut,
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment.topLeft,
                  end: Alignment.bottomRight,
                  colors: [
                    _dominantColor,
                    _dominantColor.withOpacity(0.3),
                    Colors.black,
                  ],
                  stops: const [0.0, 0.4, 1.0],
                ),
              ),
            ),
          ),

          // 2. The Foreground UI (Top of Stack)
          SafeArea(
            child: SingleChildScrollView(
              child: Column(
                children: [
                // Top bar
                Padding(
                  padding:
                      const EdgeInsets.symmetric(horizontal: 20, vertical: 8),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      IconButton(
                        icon: const Icon(Icons.keyboard_arrow_down_rounded,
                            size: 32),
                        color: kTextWhite,
                        onPressed: () => Navigator.pop(context),
                      ),
                      const Text(
                        'Now Playing',
                        style: TextStyle(
                          fontSize: 14,
                          fontWeight: FontWeight.w600,
                          color: kTextWhite,
                        ),
                      ),
                      IconButton(
                        icon: const Icon(Icons.more_vert_rounded),
                        color: kTextWhite,
                        onPressed: () {},
                      ),
                    ],
                  ),
                ),

                const SizedBox(height: 32),

                // Album art (Keep near the top/center)
                Container(
                  width: 300,
                  height: 300,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(16),
                    boxShadow: [
                      BoxShadow(
                        color: Colors.black.withOpacity(0.5),
                        blurRadius: 30,
                        offset: const Offset(0, 16),
                      ),
                    ],
                  ),
                  child: ClipRRect(
                    borderRadius: BorderRadius.circular(16),
                    child: track.thumbnail != null
                        ? Image.network(
                            track.thumbnail!,
                            fit: BoxFit.cover,
                            errorBuilder: (_, __, ___) => _placeholder(),
                          )
                        : _placeholder(),
                  ),
                ),

                const SizedBox(height: 32),

                // Title & artist
                Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 40),
                  child: Column(
                    children: [
                      Text(
                        track.title,
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                        textAlign: TextAlign.center,
                        style: const TextStyle(
                          fontSize: 22,
                          fontWeight: FontWeight.w700,
                          color: kTextWhite,
                        ),
                      ),
                      const SizedBox(height: 6),
                      MouseRegion(
                        cursor: SystemMouseCursors.click,
                        child: GestureDetector(
                          onTap: () {
                            Navigator.of(context).push(
                              MaterialPageRoute(
                                builder: (_) =>
                                    ArtistScreen(artistName: track.artist),
                              ),
                            );
                          },
                          child: Text(
                            track.artist,
                            textAlign: TextAlign.center,
                            style: const TextStyle(
                              fontSize: 14,
                              color: kTextWhite,
                              fontWeight: FontWeight.w500,
                              decoration: TextDecoration.underline,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),

                const SizedBox(height: 28),

                // 3. The Glass Pill Implementation
                // Distinct bottom container for controls, visually floating from edges
                Padding(
                  padding: const EdgeInsets.all(24.0),
                  child: ClipRRect(
                    borderRadius: BorderRadius.circular(40.0),
                    child: BackdropFilter(
                      filter: ImageFilter.blur(sigmaX: 25.0, sigmaY: 25.0),
                      child: Container(
                        padding: const EdgeInsets.symmetric(vertical: 20.0),
                        decoration: BoxDecoration(
                          color: Colors.black.withOpacity(0.2), // Smoked glass
                          borderRadius: BorderRadius.circular(40.0),
                          border: Border.all(
                            color: Colors.white.withOpacity(0.15),
                            width: 1.5,
                          ),
                        ),
                        child: Column(
                          children: [
                            // Slider inside glass pill
                            Padding(
                              padding: const EdgeInsets.symmetric(horizontal: 24),
                              child: Column(
                                children: [
                                  SliderTheme(
                                    data: SliderTheme.of(context).copyWith(
                                      trackHeight: 3,
                                      thumbShape: const RoundSliderThumbShape(enabledThumbRadius: 6),
                                      overlayShape: const RoundSliderOverlayShape(overlayRadius: 14),
                                      activeTrackColor: Colors.white,
                                      inactiveTrackColor: Colors.white.withOpacity(0.3),
                                      thumbColor: Colors.white,
                                    ),
                                    child: Slider(
                                      value: position.inMilliseconds.toDouble().clamp(
                                          0, (duration?.inMilliseconds ?? 1).toDouble()),
                                      max: (duration?.inMilliseconds ?? 1).toDouble(),
                                      secondaryTrackValue: buffered.inMilliseconds
                                          .toDouble()
                                          .clamp(
                                              0, (duration?.inMilliseconds ?? 1).toDouble()),
                                      onChanged: (v) => audioHandler
                                          .seek(Duration(milliseconds: v.toInt())),
                                    ),
                                  ),
                                  Padding(
                                    padding: const EdgeInsets.symmetric(horizontal: 8),
                                    child: Row(
                                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                      children: [
                                        Text(_fmt(position),
                                            style: const TextStyle(
                                                fontSize: 11, color: kTextWhite)),
                                        Text(_fmt(duration),
                                            style: const TextStyle(
                                                fontSize: 11, color: kTextWhite)),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            
                            const SizedBox(height: 12),
                            
                            // Buttons inside glass pill
                            Row(
                              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                              children: [
                                // Shuffle
                                Material(
                                  color: Colors.transparent,
                                  child: InkWell(
                                    borderRadius: BorderRadius.circular(24),
                                    onTap: () {
                                      ref.read(shuffleProvider.notifier).state = !shuffle;
                                    },
                                    child: Padding(
                                      padding: const EdgeInsets.all(12),
                                      child: Icon(Icons.shuffle_rounded,
                                          color: shuffle ? Colors.white : Colors.white54, size: 22),
                                    ),
                                  ),
                                ),
                                // Skip previous
                                Material(
                                  color: Colors.transparent,
                                  child: InkWell(
                                    borderRadius: BorderRadius.circular(24),
                                    onTap: () => skipPrevious(ref),
                                    child: const Padding(
                                      padding: EdgeInsets.all(8),
                                      child: Icon(Icons.skip_previous_rounded,
                                          color: Colors.white, size: 36),
                                    ),
                                  ),
                                ),
                                // Play/Pause
                                Material(
                                  color: Colors.transparent,
                                  child: InkWell(
                                    borderRadius: BorderRadius.circular(32),
                                    onTap: () => isPlaying
                                        ? audioHandler.pause()
                                        : audioHandler.play(),
                                    child: RotatingGlowingBorder(
                                      isPlayingStream: audioHandler.playbackState.map((state) => state.playing),
                                      borderWidth: 3.0,
                                      child: Container(
                                        width: 64,
                                        height: 64,
                                        decoration: BoxDecoration(
                                          shape: BoxShape.circle,
                                          color: Colors.white.withOpacity(0.9),
                                        ),
                                        child: Icon(
                                          isPlaying
                                              ? Icons.pause_rounded
                                              : Icons.play_arrow_rounded,
                                          size: 34,
                                          color: Colors.black,
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                                // Skip next
                                Material(
                                  color: Colors.transparent,
                                  child: InkWell(
                                    borderRadius: BorderRadius.circular(24),
                                    onTap: () => skipNext(ref),
                                    child: const Padding(
                                      padding: EdgeInsets.all(8),
                                      child: Icon(Icons.skip_next_rounded,
                                          color: Colors.white, size: 36),
                                    ),
                                  ),
                                ),
                                // Repeat
                                Material(
                                  color: Colors.transparent,
                                  child: InkWell(
                                    borderRadius: BorderRadius.circular(24),
                                    onTap: () {
                                      ref.read(repeatModeProvider.notifier).state =
                                          (repeatMode + 1) % 3;
                                    },
                                    child: Padding(
                                      padding: const EdgeInsets.all(12),
                                      child: Icon(
                                        repeatMode == 2
                                            ? Icons.repeat_one_rounded
                                            : Icons.repeat_rounded,
                                        color: repeatMode > 0 ? Colors.white : Colors.white54,
                                        size: 22,
                                      ),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                ),
                const SizedBox(height: 12),
              ],
            ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _placeholder() {
    return Container(
      color: kCardDark,
      child: const Center(
        child: Icon(Icons.music_note_rounded, size: 60, color: kTextMuted),
      ),
    );
  }
}
